# Generated by Django 5.1.3 on 2025-01-17 18:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_blog_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=cloudinary.models.CloudinaryField(default='images/default.jpg', max_length=255, verbose_name='image'),
        ),
    ]
